Systray fuctionality
FreeYourStream/freedeck-tools pull request #11
Opened 2021-09-22 13:59 UTC by KREATIV-LSH

Added Util to run the page switcher in a systray application on windows.
Features:
```
Systray
Pause/Unpause of automatic switching in the systray menu
Most errors get handeld so the application doesn`t crash and can run continuously
```

Goals:
```
Make a programm that is enough stable thatso  it can be an auto-start programm that will run without crashing
```

Example Image of the systray application running
![image](https://user-images.githubusercontent.com/48365347/134357615-4d0e6d15-2dc7-40d3-8b6c-e3f406eb1d37.png)

2021-09-27 21:39 UTC, koriwi requested changes
this seems to remove all linux and macos functionality. This regression is not acceptable

2021-09-28 17:24 UTC, KREATIV-LSH commented
I have now changed it so there are still the old files for linux, mac and linux but that the new systray app is in its own folder

2021-10-02 21:10 UTC, legomannetje commented on README.md
> +5. Launch the `auto_page_switch.py` script or the `systray_app.py`(only works windows). Either by double clicking on it or by navigating a console to the folder that contains the script. Then type `p
(Only works on windows) instead of (only works windows)

2021-10-02 21:12 UTC, legomannetje requested changes
Please add a pip-requirements.txt file with all the used dependencies.

2021-10-02 21:31 UTC, KREATIV-LSH commented
its the same packages as the normal python script uses so it would be the same requirements file

2021-10-18 16:42 UTC, koriwi requested changes
please remove the whitespace in the filepath "Windows SysTray" -> "Windows_SysTray"

also check your line endings. Windows changes the line endings https://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html#:~:text=Text%20files%20created%20on%20DOS,(%22%5Cn%22).

2021-10-18 21:22 UTC, luishutterli commented
Ok fixed that now!

2021-10-29 18:46 UTC, merged